
[workspace]
members = [
    "crates/wtf-rs",
    "crates/starlight",
    "crates/starlight-derive",
    "crates/benchmarks",
]
default-members = ["crates/starlight"]
[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"

[profile.bench]
debug = true
