[workspace]
members = ["crates/starlight", "crates/wtf-rs", "crates/starlight-derive"]
default-members = ["crates/starlight"]

[profile.release]
lto = true
debug = true
opt-level = 2

[profile.bench]
lto = true
debug = true
