
[workspace]
members = [
    "crates/wtf-rs",
    "crates/starlight",
    "crates/starlight-derive",
    "crates/benchmarks",
    "crates/bmalloc-rs",
    "test262-runner",
]
default-members = ["crates/starlight", "test262-runner"]
[profile.release]
debug = true
lto = "fat"
codegen-units = 3
opt-level = 's'

[profile.bench]
debug = true
opt-level = 3
lto = "off"
