[workspace]
members = ["crates/starlight", "crates/wtf-rs", "crates/starlight-derive"]
default-members = ["crates/starlight"]


[profile.release]
lto = true
opt-level = 2
debug = false
codegen-units = 1

[profile.bench]
lto = true
debug = true
