[workspace]
members = [
    "crates/starlight",
    "crates/wtf-rs",
    "crates/starlight-derive",
    "crates/libmir-sys",
]
default-members = ["crates/starlight"]


[profile.release]
lto = true
opt-level = 3
debug = true
codegen-units = 1

[profile.bench]
lto = true
debug = true
