[package]
name = "starlight"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.9"
once_cell = "1.5"
mopa = "0.2"
intrusive-collections = "0.9"
rand = "0.8"
libc = "0.2"
memmap2 = "0.2"
starlight-derive = { path = "../starlight-derive" }
wtf-rs = { path = "../wtf-rs" }
serde = { version = "1.0", optional = true }
serde-generate = { version = "0.18", optional = true }
bincode = { version = "1.3", optional = true }
ron = { version = "0.6", optional = true }
serde-reflection = { version = "0.3", optional = true }
erased-serde = { version = "0.3", optional = true }
swc_atoms = "0.2.5"
swc_common = "0.10.9"
swc_ecmascript = { version = "0.21.0", features = ["parser", "utils", "visit"] }
minivec = "0.2"
[features]
debug-snapshots = [
    "serde",
    "serde-generate",
    "bincode",
    "ron",
    "serde-reflection",
    "erased-serde",
]

valgrind-gc = []

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "bench_properties"
harness = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
