[package]
name = "starlight"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.9"
once_cell = "1.5"
mopa = "0.2"
libc = "0.2"
memmap2 = "0.2"
starlight-derive = { path = "../starlight-derive" }
wtf-rs = { path = "../wtf-rs" }
dlmalloc = "0.2"
swc_atoms = "0.2.5"
swc_common = "0.10.9"
swc_ecmascript = { version = "0.21.0", features = ["parser", "utils", "visit"] }
minivec = "0.2"
pico-args = "0.4"

[features]
malloc-gc = []
valgrind-gc = []
default = ["malloc-gc"]
compress-ptr-32 = ["compressed-ptrs"]
compress-ptr-16 = ["compressed-ptrs"]
compressed-ptrs = []

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "bench_properties"
harness = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
