[package]
name = "starlight"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mopa = "0.2"
wtf-rs = { path = "../wtf-rs" }
intrusive-collections = "0.9.0"
memmap2 = "0.2"
cfg-if = "1.0"
once_cell = "1.7.2"
dashmap = "4.0"
libc = "0.2"
libmimalloc-sys = { version = "0.1", features = ["extended"] }
starlight-derive = { path = "../starlight-derive" }
backtrace = "0.3"
crossbeam = "0.8"
[features]
val-as-f64 = []
val-as-u64 = []
enable-gc-tracking = []
# enable compressed RC which stores RC in 5 bits
compressed-rc = []
default = ["val-as-f64"]

[dev-dependencies]
criterion = "0.3"
gc = "0.4"
gc_derive = "0.4"
[[bench]]
name = "bench_tiny_alloc"
harness = false

[[bench]]
name = "bench_symbol_table"
harness = false


[[bench]]
name = "gcbench"
harness = false

[[bench]]
name = "gcbench-rc"
harness = false
[[bench]]
name = "gcbench-gc"
harness = false

[[bench]]
name = "bench_snapshot"
harness = false
