name: Rust

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup nightly
        run: rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1
      - name: Submodule update
        run: git submodule update --init
      - name: Run test262 tests
        run: cargo run --release --bin test262-runner run

  check-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup nightly
        run: rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1
      - name: Submodule update
        run: git submodule update --init
      - name: Run test262 tests
        run: cargo run --release --bin test262-runner run
  check-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup nightly
        run: rustup default nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1
      - name: Submodule update
        run: git submodule update --init
      - name: Run test262 tests
        run: cargo run --release --bin test262-runner run
